version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: szpak_portfolio_db
    environment:
      POSTGRES_DB: szpak_portfolio_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: szpak_portfolio_web
    environment:
      DATABASE_URL: ecto://postgres:postgres@db:5432/szpak_portfolio_dev
      DATABASE_HOST: db
      SECRET_KEY_BASE: your_secret_key_base_here_for_development_only
      PHX_HOST: localhost
      MIX_ENV: dev
      PHX_SERVER: "true"
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  postgres_data: